(defun delmethod ()
  (interactive)
  (let ((depth 0))
    (end-of-line)
    (while (not (bolp))
      (backward-char 1)
      ;;(prompt-for-insert "b1")
      (if (looking-at ")")
	  (setq depth (1+ depth))
	)
      (if (looking-at "(")
	  (setq depth (1- depth))
	)
      (if (looking-at ">")
	  (setq depth (1+ depth))
	)
      (if (looking-at "<")
	  (setq depth (1- depth))
	)
      (if (and (= depth 0) (looking-at ":"))
	  (progn
	    (backward-char 1)
	    (kill-line)
	    (beginning-of-line)
	    ))
      ))
  (next-line 1)
  )
