(defun demangle ()
  "Demangle Bartok output in current buffer"
  (interactive)
  (let (
	(reps '(("$L" "<")
		("$G" ">")
		("$0060" "`")
		("$0029" ")")
		("$002c" ",")
		("$0028" "(")
		("$S" "-")
		("$0021" "!")
		(" (?" "\n(?")
		("$005b" "[")
		("$005d" "]")
		("::" ".")
		("$P" "+")
		("$_" "_")
		)
	      )
	rep rep1 rep2)
    (while (not (null reps))
      (setq rep (car reps))
      (setq reps (cdr reps))
      (setq rep1 (nth 0 rep))
      (setq rep2 (nth 1 rep))
      (beginning-of-buffer)
      ;(prompt-for-insert "b1")
      (while (search-forward rep1 nil t)
	(replace-match rep2 nil t))
      )
    )
  )