;; find-grep.el - dive to file from find-grep line.

(defun dive-find-grep ()
  (interactive)
  (let (start  start2 pathname lineno (bk 0))
    ; (prompt-for-insert (int-to-string (setq bk (1+ bk))))
    (push-tag-mark)
    ; (prompt-for-insert (int-to-string (setq bk (1+ bk))))
    ; (delete-other-windows)
    ; (prompt-for-insert (int-to-string (setq bk (1+ bk))))
    ; (split-window-vertically)
    ; (prompt-for-insert (int-to-string (setq bk (1+ bk))))
    (beginning-of-line)
    ; (prompt-for-insert (int-to-string (setq bk (1+ bk))))
    (setq start (point))
    (search-forward ":")
    (setq pathname (buffer-substring start (1- (point))))
    (setq start2 (point))
    (forward-word 1)
    (setq lineno (string-to-number (buffer-substring start2 (point))))
    (message "%s %s" pathname lineno)
    (find-file pathname)
    (goto-line lineno)
    ))
